server:
  port: 8081

spring:
  main:
    allow-circular-references: true # 允许循环依赖
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: ShiXi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1t7lrt59wy71ty8xo.mysql.rds.aliyuncs.com:3306/4_uper_up_intern?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: higherDevPermissionsAdmin
    password: 4UperUpIntern
  redis:
    host: r-bp1jcvqejy2nhppxebpd.redis.rds.aliyuncs.com  # 阿里云 Redis 实例地址
    port: 6379
    username: dev_permissions_admin
    password: 4UperUpIntern  # 阿里云 Redis 密码
    lettuce:
      pool:
        max-active: 10  # 最大连接数
        max-idle: 10    # 最大空闲连接数
        min-idle: 1     # 最小空闲连接数
        time-between-eviction-runs: 10s  # 空闲连接检测周期
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: 123
    accessKeySecret: 123
    bucketName: dev-env-oss

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  elasticsearch:
    rest:
      uris: http://116.62.60.208:9200
      connection-timeout: 15000ms  # 连接超时15秒
      read-timeout: 30000ms        # 读取超时30秒



mybatis-plus:
  type-aliases-package: com.ShiXi.entity # 别名扫描包
logging:
  level:
    com.ShiXi: debug
oss:
  resume:
    dir: D:\oss\resume
feishu:
  webhook:
    url: https://open.feishu.cn/open-apis/bot/v2/hook/1c70bec6-1e50-43c5-9cb7-f7f741a8b748
aliyun:
  accessKeyId: 123
  accessKeySecret: 123

xxl:
  job:
    admin:
      # 调度中心地址（多个用逗号分隔）
      addresses: http://120.26.138.68:9999/xxl-job-admin
    executor:
      # 执行器名称（需与调度中心配置一致）
      appname: my-springboot-executor
      # 执行器端口（默认9999，若多实例需不同端口）
      port: 9998
      # 执行器注册地址（可选，默认自动获取）
      address:
      # 执行器IP（可选，默认自动获取）
      ip:
      # 日志路径
      logpath: /data/applogs/xxl-job/jobhandler
      # 日志保存天数
      logretentiondays: 30
    # 执行器与调度中心通信的accessToken（若调度中心配置了则需一致）
    accessToken: default_token
