server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: ShiXi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/4_uper_up_intern?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: 192.168.202.128  # 阿里云 Redis 实例地址
    port: 6379
    username:
    password: 1234
    lettuce:
      pool:
        max-active: 10  # 最大连接数
        max-idle: 10    # 最大空闲连接数
        min-idle: 1     # 最小空闲连接数
        time-between-eviction-runs: 10s  # 空闲连接检测周期
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: dev-env-oss
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.ShiXi.entity # 别名扫描包
logging:
  level:
    com.ShiXi: debug
oss:
  resume:
    dir: D:\oss\resume
feishu:
  webhook:
    url: https://open.feishu.cn/open-apis/bot/v2/hook/1c70bec6-1e50-43c5-9cb7-f7f741a8b748
aliyun:
  accessKeyId:
  accessKeySecret: