server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: ShiXi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1t7lrt59wy71ty8xo.mysql.rds.aliyuncs.com:3306/4_uper_up_intern?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: higherDevPermissionsAdmin
    password: 4UperUpIntern
  redis:
    host: r-bp1jcvqejy2nhppxebpd.redis.rds.aliyuncs.com  # 阿里云 Redis 实例地址
    port: 6379
    username: dev_permissions_admin
    password: 4UperUpIntern  # 阿里云 Redis 密码
    lettuce:
      pool:
        max-active: 10  # 最大连接数
        max-idle: 10    # 最大空闲连接数
        min-idle: 1     # 最小空闲连接数
        time-between-eviction-runs: 10s  # 空闲连接检测周期
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: dev-env-oss
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.ShiXi.entity # 别名扫描包
logging:
  level:
    com.ShiXi: debug