server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: ShiXi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shixi?useSSL=false&serverTimezone=UTC
    username: "root"
    password: "061532"
  redis:
    host: localhost
    port: 6379
    password: 061532
    username:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: dev-env-oss
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.ShiXi.entity # 别名扫描包
logging:
  level:
    com.ShiXi: debug
